version: 1.0

frontend:
  phases:
    preBuild:
      commands:
        - cd fe/home-worq
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: fe/home-worq/out
    files:
      - '**/*'
  cache:
    paths:
      - fe/home-worq/node_modules/**/*
